# run it with:
# docker-compose down --remove-orphans && docker image rm myenrollment:latest &&docker image prune && docker-compose up --build --force-recreate
version: "3"

services:
  app:
    image: myenrollment:latest
    build:
      context: ../
      args:
        node_env: "development"
      dockerfile: docker/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    environment:
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NODE_ENV=${NODE_ENV}
    ports:
    - 3535:3000
    networks:
      - frontend

networks:
  frontend:
# backend:
