# run it with:
# docker-compose -f docker-compose-produciton.yml down --remove-orphans && \
# docker image rm nextjs-eacon && docker image prune && \
# docker-compose -f docker-compose-produciton.yml  up --build --force-recreate
version: "3"

services:
  app:
    image: nextjs-eacon-production
    build:
      context: ../
      args:
        node_env: "development"
      dockerfile: docker/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    environment:
      - TEST
    # ports:
    # - 9191:3000
    volumes:
    #   - ../app:/app/app
    #   - ../public:/app/public
    #   - ../src:/app/src
    #   - ../styles:/app/styles
    #   - ../tailwind.config.js:/app/tailwind.config.js
    # - static_volume:/app/.next/static ./standalone/.next/static
    - static_volume:/app/standalone/.next/static
    networks:
      - frontend

  nginx:
    image: nginx:latest
    restart: always
    container_name: ${NGINX_CONTAINER_NAME}
    volumes:
      - static_volume:/home/app/web/staticfiles:Z
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - 80:80
      # - 443:443
    depends_on:
      - app
    networks:
      - frontend

volumes:
  static_volume:

networks:
  frontend:
# backend:
