# run it with:
# docker-compose down --remove-orphans && docker image rm myenrollment:latest &&docker image prune && docker-compose up --build --force-recreate
version: "3"

services:
  app:
    image: myenrollment:latest
    build:
      context: ../
      args:
        node_env: "development"
      dockerfile: docker/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    environment:
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NODE_ENV=${NODE_ENV}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    ports:
    - 3535:3000
    # volumes:
    #   - ../app:/app/app
    #   - ../public:/app/public
    #   - ../src:/app/src
    #   - ../styles:/app/styles
      # - ../tailwind.config.js:/app/tailwind.config.js
    networks:
      - frontend

  nginx:
    image: nginx:latest
    restart: always
    container_name: ${NGINX_CONTAINER_NAME}
    volumes:
      # - static_volume:/home/app/web/staticfiles:Z
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - 9191:80
    depends_on:
      - app
    networks:
      - frontend


networks:
  frontend:
